import { ApiError, apiConfig, apiRequest } from '../../../services/apiClient';
import type { Quotation, QuotationAcceptance, QuotationPayload, QuotationStatus, QuotationUpdate } from '../types';
const idPath = (id: string) => encodeURIComponent(id);
const path = (id: string) => `/api/quotations/${idPath(id)}`;
export const quotationApi = {
  list: (options: { skip?: number; limit?: number; status?: QuotationStatus } = {}) => { const query = new URLSearchParams(); if (options.skip !== undefined) query.set('skip', String(options.skip)); if (options.limit !== undefined) query.set('limit', String(options.limit)); if (options.status) query.set('status', options.status); return apiRequest<Quotation[]>(`/api/quotations${query.size ? `?${query}` : ''}`); },
  get: (id: string) => apiRequest<Quotation>(path(id)), create: (payload: QuotationPayload) => apiRequest<Quotation>('/api/quotations', { method: 'POST', body: JSON.stringify(payload) }), update: (id: string, payload: QuotationUpdate) => apiRequest<Quotation>(path(id), { method: 'PUT', body: JSON.stringify(payload) }), remove: (id: string) => apiRequest<{ message: string }>(path(id), { method: 'DELETE' }), send: (id: string) => apiRequest<Quotation>(`${path(id)}/send`, { method: 'POST' }), accept: (id: string) => apiRequest<QuotationAcceptance>(`${path(id)}/accept`, { method: 'POST' }), reject: (id: string) => apiRequest<Quotation>(`${path(id)}/reject`, { method: 'POST' }), requestRevision: (id: string) => apiRequest<Quotation>(`${path(id)}/request-revision`, { method: 'POST' }),
  download: async (id: string, quotationNumber: string) => { const token = sessionStorage.getItem('upserve.accessToken'); const response = await fetch(`${apiConfig.baseUrl}${path(id)}/pdf`, { headers: token ? { Authorization: `Bearer ${token}` } : {} }); if (!response.ok) throw new ApiError(response.status, response.status === 403 ? 'You do not have access to this quotation.' : response.status === 404 ? 'Quotation PDF was not found.' : 'Unable to download the quotation PDF.'); const url = URL.createObjectURL(await response.blob()); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `quotation_${quotationNumber}.pdf`; document.body.appendChild(anchor); anchor.click(); anchor.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); },
};
