import { useEffect, useState, type FormEvent } from 'react';
import type { Deliverable, DeliverablePayload } from '../types';

type Props = { initial?: Deliverable; busy: boolean; onSubmit: (payload: DeliverablePayload) => void; onCancel: () => void };
export function DeliverableForm({ initial, busy, onSubmit, onCancel }: Props) {
  const [form, setForm] = useState<DeliverablePayload>({ title: initial?.title ?? '', description: initial?.description ?? '', dueDate: initial?.dueDate?.slice(0, 10) ?? '', clientVisible: initial?.clientVisible ?? true, notes: initial?.notes ?? '' });
  const [error, setError] = useState(''); const [dirty, setDirty] = useState(false);
  useEffect(() => { if (!dirty || typeof window === 'undefined') return undefined; const warn = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ''; }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
  const set = (key: keyof DeliverablePayload, value: string | boolean) => { setForm(previous => ({ ...previous, [key]: value })); setDirty(true); setError(''); };
  function submit(event: FormEvent) { event.preventDefault(); const title = form.title.trim(); if (title.length < 2) { setError('Add a deliverable title with at least two characters.'); return; } if (form.dueDate && Number.isNaN(new Date(form.dueDate).getTime())) { setError('Choose a valid due date.'); return; } setError(''); onSubmit({ ...form, title, description: form.description?.trim() || undefined, dueDate: form.dueDate || undefined, notes: form.notes?.trim() || undefined }); }
  function cancel() { if (!dirty || window.confirm('Leave this deliverable? Your unsaved changes will be lost.')) onCancel(); }
  return <form className="deliverable-form" onSubmit={submit} noValidate>{error && <div className="error" role="alert">{error}</div>}<div className="form-grid"><label>Title <span className="required-mark">*</span><input required maxLength={200} value={form.title} onChange={event => set('title', event.target.value)} placeholder="e.g. Responsive marketing website" /></label><label>Due date <span className="optional">Optional</span><input type="date" value={form.dueDate ?? ''} onChange={event => set('dueDate', event.target.value)} /></label></div><label>Description <span className="optional">Optional</span><textarea rows={3} value={form.description ?? ''} onChange={event => set('description', event.target.value)} placeholder="What will be delivered?" /></label><label>Notes <span className="optional">Optional</span><textarea rows={2} value={form.notes ?? ''} onChange={event => set('notes', event.target.value)} placeholder="Internal context or handoff notes" /></label><label className="checkbox-label"><input type="checkbox" checked={form.clientVisible} onChange={event => set('clientVisible', event.target.checked)} /> Visible to client</label><div className="actions"><button disabled={busy}>{busy ? 'Saving…' : initial ? 'Save changes' : 'Create deliverable'}</button><button type="button" className="secondary" disabled={busy} onClick={cancel}>Cancel</button></div></form>;
}
