import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { useAuth } from '../../../context/AuthContext';
import { authApi } from '../../../services/authApi';
import { ApiError } from '../../../services/apiClient';
import { LeadForm } from '../components/LeadForm';
import { LeadHistory } from '../components/LeadHistory';
import { LeadStatusBadge } from '../components/LeadStatusBadge';
import { LeadRequirementsSection } from '../../requirements/components/LeadRequirementsSection';
import { UserIdentity } from '../../../components/UserIdentity';
import { leadApi } from '../services/leadApi';
import type { Lead, LeadHistoryEvent } from '../types';
import { LoadingState, useConfirm } from '../../../components/ui';

const message = (error: unknown) => error instanceof ApiError ? error.message : error instanceof Error ? error.message : 'Unable to complete the request.';

export function LeadDetailPage() {
  const { leadId } = useParams(); const navigate = useNavigate(); const { user } = useAuth();
  const [lead, setLead] = useState<Lead | null>(null); const [history, setHistory] = useState<LeadHistoryEvent[]>([]); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [conversionResult, setConversionResult] = useState<Pick<Lead, 'accountStatus' | 'emailStatus' | 'emailMessage'> | null>(null); const [busy, setBusy] = useState(false); const [editing, setEditing] = useState(false); const [password, setPassword] = useState(''); const [newAccount, setNewAccount] = useState(false); const [assignEmail, setAssignEmail] = useState('');
  const requestVersion = useRef(0);
  const activeId = useRef(leadId);
  const admin = user?.role !== 'client'; const superAdmin = user?.role === 'super_admin';
  const confirm = useConfirm();
  async function refresh() { const targetId = activeId.current; if (!targetId) return; const version = ++requestVersion.current; setError(''); try { const [nextLead, nextHistory] = await Promise.all([leadApi.get(targetId), leadApi.history(targetId)]); if (version !== requestVersion.current || targetId !== activeId.current) return; setLead(nextLead); setHistory(nextHistory); } catch (value) { if (version === requestVersion.current && targetId === activeId.current) setError(message(value)); } }
  useEffect(() => { activeId.current = leadId; requestVersion.current += 1; setLead(null); setHistory([]); setError(''); void refresh(); }, [leadId]);
  async function action(fn: () => Promise<Lead>, after?: (next: Lead) => void, successMessage = 'Lead updated successfully.') { setBusy(true); setError(''); setSuccess(''); try { const next = await fn(); setLead(next); after?.(next); if (leadId) setHistory(await leadApi.history(leadId)); setSuccess(successMessage); } catch (value) { setError(message(value)); await refresh(); } finally { setBusy(false); } }
  if (error && !lead) return <section className="page"><Link to="/app/leads"><ArrowLeft size={16} aria-hidden="true" /> Back to leads</Link><div className="error" role="alert">{error}</div></section>;
  if (!lead) return <LoadingState label="Loading lead" />;
  const currentLead = lead;
  const terminal = currentLead.stage === 'Lost';
  const canConvert = !currentLead.clientId && currentLead.stage !== 'Lost';
  async function convert() { if (await confirm({ title: 'Convert lead', message: 'Upserve will create a new client account or link the existing account for this email. No existing password will be changed.', destructive: true })) await action(() => leadApi.convert(currentLead.id, newAccount ? password.trim() || undefined : undefined), next => { setPassword(''); setNewAccount(false); setConversionResult({ accountStatus: next.accountStatus, emailStatus: next.emailStatus, emailMessage: next.emailMessage }); }, 'Lead converted to client.'); }
  async function confirmStage(next: 'won' | 'lost') { if (await confirm({ title: `Mark lead ${next}`, message: `This is a terminal action. The lead cannot be moved further after it is marked ${next}.`, destructive: next === 'lost' })) await action(() => next === 'won' ? leadApi.markWon(currentLead.id) : leadApi.markLost(currentLead.id)); }
  async function assignByEmail(): Promise<Lead> { const email = assignEmail.trim(); if (!email) throw new Error('Enter a Sub Admin email.'); const subAdmin = await authApi.lookupSubAdmin(email); return leadApi.assign(currentLead.id, subAdmin.id); }
  return <section className="page lead-detail-page"><Link className="back-link" to="/app/leads">← Back to leads</Link><div className="page-heading"><div><p className="eyebrow">CRM lead</p><h1>{currentLead.companyName || currentLead.contactPerson}</h1><div className="lead-heading-meta"><LeadStatusBadge stage={currentLead.stage} /><span className="muted">{currentLead.email}</span></div></div><div className="actions">{!terminal && admin && <button className="secondary" disabled={busy} onClick={() => setEditing(value => !value)}>{editing ? 'Close edit' : 'Edit lead'}</button>}</div></div>{error && <div className="error" role="alert">{error}</div>}{success && <div className="success" role="status">{success}</div>}{conversionResult && <div className={`conversion-result ${conversionResult.emailStatus === 'failed' ? 'is-warning' : ''}`} role="status"><strong>{conversionResult.accountStatus === 'created' ? 'New client account created.' : 'Existing client account linked.'}</strong><span>{conversionResult.emailMessage}</span></div>}{editing && <LeadForm initial={currentLead} busy={busy} onSubmit={payload => void action(() => leadApi.update(currentLead.id, payload), () => setEditing(false), 'Lead changes saved.')} onCancel={() => setEditing(false)} />}
    <div className="lead-detail-grid"><section className="card lead-information-card"><div className="section-heading"><div><p className="eyebrow">Opportunity profile</p><h2>Lead information</h2></div><span className="muted">Created {new Date(lead.createdAt).toLocaleDateString()}</span></div><dl className="lead-fields"><div><dt>Contact person</dt><dd>{lead.contactPerson}</dd></div><div><dt>Email</dt><dd><a href={`mailto:${lead.email}`}>{lead.email}</a></dd></div><div><dt>Phone</dt><dd>{lead.phone || 'Not provided'}</dd></div><div><dt>Company</dt><dd>{lead.companyName || 'Not provided'}</dd></div><div><dt>Business</dt><dd>{lead.business}</dd></div><div><dt>Lead source</dt><dd>{lead.leadSource || 'Not specified'}</dd></div><div><dt>Assigned Sub Admins</dt><dd>{(lead.assignedToIds?.length ? lead.assignedToIds : lead.assignedTo ? [lead.assignedTo] : []).map(id => <span key={id} className="relationship-connected"><UserIdentity id={id} /></span>)}{!lead.assignedTo && !lead.assignedToIds?.length && <span className="muted">Unassigned</span>}</dd></div><div><dt>Client relationship</dt><dd>{lead.clientId ? <span className="relationship-connected">Client account connected</span> : 'Client account not created yet'}</dd></div></dl>{lead.notes && <div className="lead-notes"><h3>Working notes</h3><p>{lead.notes}</p></div>}</section>
      <section className="card lead-actions-card"><div className="lead-action-heading"><div><p className="eyebrow">Lifecycle control</p><h2>Next action</h2></div><LeadStatusBadge stage={lead.stage} /></div><p className="muted">{lead.stage === 'Won' ? 'Complete ownership and client setup before delivery begins.' : 'Move this opportunity through the CRM lifecycle.'}</p>{terminal ? <div className="lead-terminal-message"><strong>This lead is lost.</strong><span>Lost leads are closed and cannot be changed.</span></div> : <div className="lead-action-stack"><div className="actions">{lead.stage !== 'Won' && <button disabled={busy} onClick={() => confirmStage('won')}>Mark as won</button>}<button className="secondary" disabled={busy} onClick={() => confirmStage('lost')}>Mark as lost</button></div>{superAdmin && <div className="lead-assignment"><h3>Assign ownership</h3><p className="field-help">Add active Sub Admins. Existing assignments stay attached to this lead.</p><div className="inline-field"><input type="email" value={assignEmail} placeholder="subadmin@example.com" onChange={e => setAssignEmail(e.target.value)} /><button className="secondary" disabled={busy || !assignEmail.trim()} onClick={() => action(assignByEmail, () => setAssignEmail(''), 'Sub Admin added to this lead.')}>Add</button></div></div>}{canConvert && <div className="lead-convert"><h3>Convert to client</h3><p className="field-help">{currentLead.clientId ? 'A client account is already connected.' : 'Create or link the client account. This can be completed after the lead is won.'}</p>{!currentLead.clientId && <><button type="button" className="text-button conversion-password-toggle" onClick={() => setNewAccount(value => !value)}>{newAccount ? 'Use existing client path' : 'Set a password for a new client account'}</button>{newAccount && <input type="password" aria-label="New client password" minLength={8} placeholder="New client password (new account only)" value={password} onChange={e => setPassword(e.target.value)} />}</>}<button disabled={busy} onClick={() => void convert()}>{busy ? 'Converting…' : 'Create/link client account'}</button></div>}</div>}</section></div>
    <LeadRequirementsSection leadId={currentLead.id} canCreate={false} />
    <section className="card lead-history-card"><div className="section-heading"><div><h2>Activity history</h2><p className="muted">A record of changes and lifecycle actions.</p></div><button className="secondary" disabled={busy} onClick={() => void refresh()}>Refresh</button></div><LeadHistory events={history} /></section>
  </section>;
}
