import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../../context/AuthContext';
import { ApiError } from '../../../services/apiClient';
import { leadApi } from '../services/leadApi';
import { leadStages, type Lead, type LeadStage } from '../types';
import { LeadForm } from '../components/LeadForm';
import { LeadTable } from '../components/LeadTable';

const errorMessage = (error: unknown) => error instanceof ApiError ? error.message : error instanceof Error ? error.message : 'Unable to complete the request.';

export function LeadsPage() {
  const { user } = useAuth();
  const canCreate = user?.role !== 'client';
  const [leads, setLeads] = useState<Lead[]>([]); const [stage, setStage] = useState<LeadStage | ''>(''); const [search, setSearch] = useState(''); const [skip, setSkip] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [showForm, setShowForm] = useState(false); const [busy, setBusy] = useState(false); const limit = 25;
  const visibleLeads = useMemo(() => { const query = search.trim().toLowerCase(); if (!query) return leads; return leads.filter(lead => [lead.contactPerson, lead.email, lead.companyName, lead.business].some(value => value?.toLowerCase().includes(query))); }, [leads, search]);
  async function refresh() { setLoading(true); setError(''); try { setLeads(await leadApi.list({ skip, limit, stage: stage || undefined })); } catch (value) { setError(errorMessage(value)); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, [skip, stage]);
  async function create(payload: Parameters<typeof leadApi.create>[0]) { setBusy(true); setError(''); try { await leadApi.create(payload); setShowForm(false); if (skip === 0) await refresh(); else setSkip(0); } catch (value) { const detail = errorMessage(value); setError(detail.toLowerCase().includes('email') ? `${detail} If this contact already exists, open the existing lead instead of creating a duplicate.` : detail); } finally { setBusy(false); } }
  const hasFilters = Boolean(search.trim() || stage);
  const clearFilters = () => { setSearch(''); setStage(''); setSkip(0); };
  return <section className="page leads-page"><div className="page-heading"><div><p className="eyebrow">Customer relationship management</p><h1>Leads</h1><p className="muted">Manage opportunities, ownership and the path from first contact to client.</p></div>{canCreate && <button type="button" onClick={() => setShowForm(value => !value)}>{showForm ? 'Close form' : 'Create lead'}</button>}</div>{error && <div className="error" role="alert">{error}</div>}{showForm && <LeadForm busy={busy} onSubmit={payload => void create(payload as Parameters<typeof leadApi.create>[0])} onCancel={() => setShowForm(false)} />}<div className="card leads-list-card"><div className="section-heading"><div><h2>Pipeline</h2><p className="muted">{leads.length ? `${visibleLeads.length} lead${visibleLeads.length === 1 ? '' : 's'} visible to your role.` : 'No leads match the selected stage.'}</p></div><div className="lead-toolbar"><label className="search-field">Search leads<input type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Name, company or email" /></label><label className="filter-field">Stage<select value={stage} onChange={e => { setStage(e.target.value as LeadStage | ''); setSkip(0); }}><option value="">All stages</option>{leadStages.map(value => <option key={value} value={value}>{value}</option>)}</select></label>{hasFilters && <button type="button" className="text-button lead-clear-filters" onClick={clearFilters}>Clear filters</button>}</div></div>{loading ? <div className="screen-state" role="status" aria-busy="true">Loading leads…</div> : leads.length && visibleLeads.length ? <><LeadTable leads={visibleLeads} /><div className="pagination" aria-label="Lead pagination"><button type="button" className="secondary" disabled={!skip || loading} onClick={() => setSkip(Math.max(0, skip - limit))}>Previous</button><span className="muted">Showing {skip + 1}–{skip + leads.length}</span><button type="button" className="secondary" disabled={leads.length < limit || loading} onClick={() => setSkip(skip + limit)}>Next</button></div></> : leads.length ? <div className="empty-state"><h3>No matching leads</h3><p className="muted">Try a different name, company or email.</p><button type="button" className="secondary" onClick={clearFilters}>Clear filters</button></div> : <div className="empty-state"><h3>No leads yet</h3><p className="muted">Create a lead to begin your pipeline.</p>{canCreate && <Link className="button-link" to="#create" onClick={() => setShowForm(true)}>Create your first lead</Link>}</div>}</div></section>;
}
