import { useEffect, useMemo, useState } from 'react';
import { ApiError } from '../../../services/apiClient';
import { notificationApi } from '../services/notificationApi';
import type { Notification } from '../types';
import { NotificationList } from '../components/NotificationList';
import { Bell, CheckCircle2, RefreshCw } from 'lucide-react';
import { useConfirm } from '../../../components/ui';

const errorMessage = (error: unknown) => error instanceof ApiError ? error.message : error instanceof Error ? error.message : 'Unable to load notifications.';

export function NotificationsPage() {
  const confirm = useConfirm();
  const [items, setItems] = useState<Notification[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [filter, setFilter] = useState<'all' | 'unread'>('all');
  const unreadCount = useMemo(() => items.filter(item => !item.read).length, [items]);
  async function refresh() { setLoading(true); setError(''); try { setItems(await notificationApi.list()); } catch (value) { setError(errorMessage(value)); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, []);
  async function action(fn: () => Promise<unknown>, success?: string) { setBusy(true); setError(''); setNotice(''); try { await fn(); await refresh(); window.dispatchEvent(new Event('upserve:notifications-changed')); if (success) setNotice(success); } catch (value) { setError(errorMessage(value)); } finally { setBusy(false); } }
  const visibleItems = filter === 'unread' ? items.filter(item => !item.read) : items;
  return <section className="page notifications-page"><div className="page-heading notifications-heading"><div><p className="eyebrow">Your workspace</p><h1>Notifications</h1><p className="muted">Stay on top of project activity and important account updates.</p></div><div className="notification-page-actions">{unreadCount > 0 && <button className="secondary" disabled={busy} onClick={() => void action(() => notificationApi.markAllRead(), 'All notifications marked as read.')}>Mark all read</button>}{items.length > 0 && <button className="secondary danger-action" disabled={busy} onClick={async () => { if (await confirm({ title: 'Clear notifications', message: 'This permanently deletes all notifications.', destructive: true })) void action(() => notificationApi.clearAll(), 'Notifications cleared.'); }}>Clear all</button>}</div></div>{error && <div className="error notification-error" role="alert"><span>{error}</span><button type="button" className="text-button" onClick={() => void refresh()} disabled={loading}>Try again</button></div>}{notice && <div className="success" role="status">{notice}</div>}{loading ? <div className="card screen-state" role="status"><RefreshCw className="ui-spinner" size={20} aria-hidden="true" />Loading notifications…</div> : items.length === 0 ? <div className="card empty-state notification-empty"><div className="empty-state-icon" aria-hidden="true"><CheckCircle2 size={20} /></div><h2>You’re all caught up</h2><p>New project updates and account activity will appear here.</p></div> : <section className="card notifications-card"><div className="notifications-card-header"><div><h2><Bell size={18} aria-hidden="true" /> Inbox</h2><span className="muted">{unreadCount ? `${unreadCount} unread` : 'All caught up'}</span></div><div className="notification-filters" role="tablist" aria-label="Notification filter"><button type="button" role="tab" aria-selected={filter === 'all'} className={filter === 'all' ? 'is-active' : ''} onClick={() => setFilter('all')}>All <span>{items.length}</span></button><button type="button" role="tab" aria-selected={filter === 'unread'} className={filter === 'unread' ? 'is-active' : ''} onClick={() => setFilter('unread')}>Unread <span>{unreadCount}</span></button></div></div>{visibleItems.length ? <NotificationList items={visibleItems} busy={busy} onRead={item => void action(() => notificationApi.markRead(item.id), 'Notification marked as read.')} onDelete={item => void action(() => notificationApi.remove(item.id), 'Notification deleted.')} /> : <div className="notification-filter-empty"><CheckCircle2 size={20} aria-hidden="true" /><p>No unread notifications.</p></div>}</section>}</section>;
}
